# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GAMA.UI'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 481)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(-13, -70, 851, 551))
        self.bg.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"\n"
"")
        self.bg.setText("")
        self.bg.setObjectName("bg")
        self.BGBORDER = QtWidgets.QLabel(self.centralwidget)
        self.BGBORDER.setGeometry(QtCore.QRect(0, 0, 801, 481))
        self.BGBORDER.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border:6px solid red;")
        self.BGBORDER.setText("")
        self.BGBORDER.setObjectName("BGBORDER")
        self.GIF = QtWidgets.QLabel(self.centralwidget)
        self.GIF.setGeometry(QtCore.QRect(10, 10, 311, 281))
        self.GIF.setStyleSheet("")
        self.GIF.setText("")
        self.GIF.setPixmap(QtGui.QPixmap("../Siri.gif"))
        self.GIF.setScaledContents(True)
        self.GIF.setObjectName("GIF")
        self.TERMINAL = QtWidgets.QLabel(self.centralwidget)
        self.TERMINAL.setGeometry(QtCore.QRect(10, 410, 431, 61))
        self.TERMINAL.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"BORDER: 3PX SOLID RED;")
        self.TERMINAL.setText("")
        self.TERMINAL.setObjectName("TERMINAL")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(450, 340, 341, 61))
        self.textBrowser.setStyleSheet("border: 3px solid red ;")
        self.textBrowser.setObjectName("textBrowser")
        self.GIF2 = QtWidgets.QLabel(self.centralwidget)
        self.GIF2.setGeometry(QtCore.QRect(447, 10, 341, 321))
        self.GIF2.setStyleSheet("")
        self.GIF2.setText("")
        self.GIF2.setPixmap(QtGui.QPixmap("../initialializing.gif"))
        self.GIF2.setScaledContents(True)
        self.GIF2.setObjectName("GIF2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(450, 410, 181, 61))
        self.pushButton.setStyleSheet("border:3px solid red;\n"
"font: 75 25pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(620, 410, 161, 61))
        self.pushButton_2.setStyleSheet("border:3px solid red;\n"
"font: 75 25pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9.6pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; font-weight:600;\">TIME:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.pushButton_2.setText(_translate("MainWindow", "CLOSE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
